# Generated by Django 4.0.2 on 2022-02-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('pool_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('bet_data', models.TextField(default='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default=None, max_length=200)),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('finish_date', models.DateField()),
                ('is_active', models.IntegerField(default=0)),
                ('is_private', models.IntegerField(default=0)),
                ('theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pool_admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('is_admin', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=150)),
                ('question_description', models.CharField(default='', max_length=500)),
                ('question_data', models.TextField(default='')),
                ('image', models.CharField(default=None, max_length=200)),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('question_type', models.CharField(max_length=200)),
                ('pool_id', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('image', models.CharField(default='', max_length=200)),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
