# Generated by Django 4.0.2 on 2022-02-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_bet_hash_id_alter_pool_hash_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='hash_id',
            field=models.CharField(default='dba74ac7905111ec994f24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hash_id',
            field=models.CharField(default='dba74ac9905111ec8cdf24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.CharField(default='dba74ac8905111eca1ed24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool_admins',
            name='hash_id',
            field=models.CharField(default='dba798e7905111ec879e24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hash_id',
            field=models.CharField(default='dba771ca905111eca4e024f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(default='dba771c9905111ec9a1724f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='dba723aa905111ec89a424f5aa5b0c45', max_length=200, null=True),
        ),
    ]
