# Generated by Django 4.0.2 on 2022-02-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_bet_hash_id_alter_pool_hash_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='hash_id',
            field=models.CharField(default='5a56909795c911ecad8d24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='finish_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hash_id',
            field=models.CharField(default='5a56b7c095c911ec91f424f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.CharField(default='5a56b7bf95c911ecb09224f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool_admins',
            name='hash_id',
            field=models.CharField(default='5a5705d095c911ec9ccd24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hash_id',
            field=models.CharField(default='5a56deca95c911ec960b24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(default='5a56dec995c911ec946024f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='5a56909695c911eca2c924f5aa5b0c45', max_length=200, null=True),
        ),
    ]
