# Generated by Django 4.0.2 on 2022-02-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_bet_hash_id_alter_pool_finish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='theme',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='bet',
            name='hash_id',
            field=models.CharField(default='b1232d0095cd11eca9b924f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hash_id',
            field=models.CharField(default='b1232d0295cd11eca65924f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.CharField(default='b1232d0195cd11ecbd5624f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool_admins',
            name='hash_id',
            field=models.CharField(default='b1237b1895cd11eca48424f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hash_id',
            field=models.CharField(default='b123540995cd11ec9edd24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(default='b123540895cd11eca96224f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='b122dedc95cd11ec868a24f5aa5b0c45', max_length=200, null=True),
        ),
    ]
