# Generated by Django 4.0.2 on 2022-02-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_theme_pool_type_alter_bet_hash_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='password',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='hash_id',
            field=models.CharField(default='4e1505d395ce11ecaddf24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hash_id',
            field=models.CharField(default='4e152cf995ce11ec9e2f24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='image',
            field=models.CharField(default='4e152cf895ce11ec806424f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool_admins',
            name='hash_id',
            field=models.CharField(default='4e157b0995ce11ecb84d24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hash_id',
            field=models.CharField(default='4e15540695ce11eca01224f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(default='4e15540595ce11ecae9424f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='4e1505d295ce11ec849224f5aa5b0c45', max_length=200, null=True),
        ),
    ]
