# Generated by Django 4.0.2 on 2022-03-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_bet_hash_id_alter_pool_hash_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='hash_id',
            field=models.CharField(default='0556b08da0d711ec9df924f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hash_id',
            field=models.CharField(default='0556d78fa0d711ec8a5324f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool_admins',
            name='hash_id',
            field=models.CharField(default='0556fe96a0d711ecbedd24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hash_id',
            field=models.CharField(default='0556d790a0d711ecbacd24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='0556897aa0d711ecada524f5aa5b0c45', max_length=200, null=True),
        ),
    ]
