# Generated by Django 4.0.2 on 2022-03-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_bet_hash_id_alter_pool_hash_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='finish_date',
        ),
        migrations.AddField(
            model_name='pool',
            name='poll_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bet',
            name='hash_id',
            field=models.CharField(default='d0c96230a4aa11ec891024f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hash_id',
            field=models.CharField(default='d0c9b04aa4aa11ecbf8b24f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool_admins',
            name='hash_id',
            field=models.CharField(default='d0c9fe4fa4aa11eca94324f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hash_id',
            field=models.CharField(default='d0c9d763a4aa11ecade324f5aa5b0c45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(default='d0c93b1ca4aa11ecb04124f5aa5b0c45', max_length=200, null=True),
        ),
    ]
