# Generated by Django 4.0.2 on 2022-03-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_pool_finish_date_pool_poll_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='hash_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hash_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pool_admins',
            name='hash_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='hash_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
