# Generated by Django 4.0.2 on 2022-03-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_bet_hash_id_alter_pool_hash_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pool',
            new_name='poll',
        ),
        migrations.RenameModel(
            old_name='pool_admins',
            new_name='poll_admins',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='pool_id',
            new_name='poll_id',
        ),
        migrations.RenameField(
            model_name='poll_admins',
            old_name='pool_id',
            new_name='poll_id',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='pool_id',
            new_name='poll_id',
        ),
    ]
