# Generated by Django 4.0.2 on 2022-07-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_pool_poll_rename_pool_admins_poll_admins_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='question_id',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bet',
            name='answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bet',
            name='image',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
