# Generated by Django 3.2.16 on 2023-06-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_delete_questions_rename_question_id_bet_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
