# Generated by Django 3.2.16 on 2023-06-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_poll_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='type',
            new_name='poll_type',
        ),
        migrations.AddField(
            model_name='bet',
            name='finish_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='finish_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
