# Generated by Django 3.2.16 on 2023-06-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20230623_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
