# Generated by Django 4.2.7 on 2023-11-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20230624_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('hash_id', models.CharField(default=None, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_ip', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
