# Generated by Django 4.2.23 on 2025-06-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('bet_id', models.IntegerField(default=0)),
                ('answer', models.CharField(default='', max_length=200)),
                ('bet_data', models.TextField(default='')),
                ('hash_id', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
    ]
