# Generated by Django 4.2.23 on 2025-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_user_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bet',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
